### ISSUE TITLE
Pronunciation guides should be recognized and not counted towards buzzes

### ISSUE THREAD

**Issue by correct-horse-battery-staple** [alopezlago/MODAQ#91] opened 2021-07-05 16:01 UTC
Pronunciation guides can add several extra words into a tossup, which can shift the buzzpoint data. This same problem also happens with the power mark.

**Comment by alopezlago** [comment] 2021-07-05 17:07
Duplicate of #45. One challenge is that pronunciation guides are formatted differently between packets (using () vs []). This should now be doable since #17 is completed. I was planning to do some refactoring work around controllers, and then to work on handling pronunciation guides.

I'm surprised to hear that power marks shift buzzpoint data; is the power marker correct in your game format? You can check it from Options | Change Format.... When I look at a packet with powers, MODAQ correctly skips the power marker when counting words (which you should be able to see in the DOM in the data-index property).

**Comment by correct-horse-battery-staple** [comment] 2021-07-07 00:18
Took another look and the power marking issue was just me speeding through menus and not selecting the appropriate format (i.e. one with powers), so that's resolved.

**Comment by alopezlago** [comment] 2021-07-07 02:18
Okay. Closing this as a dupe then, and tracking it through #45

**Closed by alopezlago** 2021-07-07 02:18 UTC
Labels: duplicate
