### ISSUE TITLE
Removed players' names are still suggested in Substitute/Remove dropdown

### ISSUE THREAD

**Issue by vcpavao** [alopezlago/MODAQ#179] opened 2022-11-14 00:09 UTC
Steps to replicate:

1. Select 'Add Player' from Actions dropdown
2. Add a player
3. Select 'Substitute/Remove' from Actions dropdown
4. Remove player you added from team
5. Select 'Substitute/Remove' from Actions dropdown
6. Player's name is still suggested for a substitution

**Comment by alopezlago** [comment] 2022-11-14 00:29
May be related to #117 and its fix

**Comment by alopezlago** [comment] 2022-11-17 02:54
This would require some potentially big changes in how we track players, and might not be the correct design anyway. A player could leave and come back, although it would be weird to have them be a substitute in that case.

**Comment by alopezlago** [comment] 2023-10-27 06:41
This actually might be a good design. People can leave and join back later, for example taking emergency calls.

**Comment by alopezlago** [comment] 2023-12-30 00:18
Going to close this as By Design

**Closed by alopezlago** 2023-12-30 00:18 UTC
Labels: question, Low priority

**Comment by hftf** [comment] 2023-12-30 18:00
Is the confusion one of terminology? "add/remove" vs. "sub in/sub out"
